development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:87c54c3bba71b145cbabcf6039ef8345@spinyfin.redistogo.com:11701/
  channel_prefix: schwack_production
